### ISSUE TITLE
Using images of a 3d model as input data

### ISSUE THREAD

**Issue by MegusarVid** [thmoa/semantic_human_texture_stitching#1]
Hello, i have been trying to reporduce your results, but i cant seem to get a detailed enough texture. 
I was wondering why are you using pictures of a 3d model as input data in your sample.
I was also wondering for the setting of captured video, how careful should i be about lighting conditions and such things.
Thanks

**Comment by thmoa** [comment]
Please refer to the paper. It seems you are not 100% aware of what the software is doing.
