### ISSUE TITLE
Getting an error while running run_sample.sh

### ISSUE THREAD

**Issue by vineethbabu** [thmoa/semantic_human_texture_stitching#11]
I got your Octopus project running correctly earlier and I was trying to get the texture mapping also done. I got all the dependencies installed correctly. 
However when I was running the run_sample.sh, I got this error: Can you please tell what could be the reason"? 
Step 1: make unwraps...
100%|██████████| 8/8 [00:22<00:00,  2.86s/it]
Step 2: make priors...
extract from 0000_unwrap.jpg...
extract from 0001_unwrap.jpg...
extract from 0002_unwrap.jpg...
extract from 0003_unwrap.jpg...
extract from 0004_unwrap.jpg...
extract from 0005_unwrap.jpg...
extract from 0006_unwrap.jpg...
extract from 0007_unwrap.jpg...
GMM fit Shoes...
GMM fit Torso-skin...
GMM fit Arms...
GMM fit Face...
GMM fit Hair...
GMM fit UpperClothes...
GMM fit Pants...
Traceback (most recent call last):
  File "step2_segm_vote_gmm.py", line 146, in <module>
    main(args.unwrap_dir, args.segm_out_file, args.gmm_out_file)
  File "step2_segm_vote_gmm.py", line 106, in main
    gc = gco.gco()
AttributeError: 'module' object has no attribute 'gco'
Step 3: stitch texture...
Traceback (most recent call last):
  File "step3_stitch_texture.py", line 83, in <module>
    main(args.unwrap_dir, args.segm_template, args.gmm, args.out_file, args.iter)
  File "step3_stitch_texture.py", line 24, in main
    segm_template = read_segmentation(segm_template_file)
  File "/home/drive/semantic_human_texture_stitching/util/labels.py", line 77, in read_segmentation
    segm = cv2.imread(file)[:, :, ::-1]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by thmoa** [comment]
See error and fix it.

> AttributeError: 'module' object has no attribute 'gco'

**Comment by Jinfeng-Jiang** [comment]
Have you fix it? I meet the same problem.

**Comment by Jinfeng-Jiang** [comment]
I have fixed it.
Rewrite the code "gc = gco.gco()"  to  "gc = gco.GCO()"  and gc.createGeneralGraph() to gc.create_general_graph() in file "step2_segm_vote_gmm.py" and file "step3_stitch_texture.py".

**Comment by shehan0** [comment]
> I have fixed it.
> Rewrite the code "gc = gco.gco()" to "gc = gco.GCO()" and gc.createGeneralGraph() to gc.create_general_graph() in file "step2_segm_vote_gmm.py" and file "step3_stitch_texture.py".

Thanks man. This worked for me.

**Comment by yutao007** [comment]
> I have fixed it.
> Rewrite the code "gc = gco.gco()" to "gc = gco.GCO()" and gc.createGeneralGraph() to gc.create_general_graph() in file "step2_segm_vote_gmm.py" and file "step3_stitch_texture.py".

i do this  but it still wrong
