### ISSUE TITLE
Change Texture Map mask

### ISSUE THREAD

**Issue by alakhag** [thmoa/semantic_human_texture_stitching#13]
I want to change the mask provided with this repository.
This repository provides this mask:
![old_mask](https://user-images.githubusercontent.com/24429931/65793731-2231a400-e12c-11e9-983d-7351f9e19346.png)

However, I want to use this mask, extracted from the People's Snapshot Dataset:
![tex_mask_1000](https://user-images.githubusercontent.com/24429931/65793768-3a092800-e12c-11e9-8069-9580966a0dcd.png)
How can I do that?

**Comment by thmoa** [comment]
2 is just a dilated version of 1

**Comment by alakhag** [comment]
Could be. However, I generated by thresholding the texture map given in the People Snapshot dataset. The first mask does not stick properly with obj file produced from Octopus. It produces black stitching lines at the edges. The texture from the second mask (that I got from People Snapshot dataset) covers the obj model very well.

**Comment by thmoa** [comment]
Simply inpaint or dilate the obtained texture.

**Comment by thmoa** [comment]
See 7beaa44
