### ISSUE TITLE
Texturing solution? 

### ISSUE THREAD

**Issue by ZhiRuoo** [thmoa/semantic_human_texture_stitching#14]
@alakhag, as mentioned by you I followed the steps and now my Material file ("mymtl.mtl") now looks like this: 

#Blender MTL File: 'None'
#Material Count: 1

newmtl MyMaterial
Ns 0
Ka 1.000000 1.000000 1.000000
Kd 0.400000 0.400000 0.400000
Ks 0.000000 0.000000 0.000000
d 1.000000
illum 2
map_Ka sample_texture.jpg

Then I downloaded the SMPL model (fbx), converted to OBJ and copied the vt and f vertices into the Octopus generated obj. 

Before that, I removed the f co-ords from Octopus obj. 

Now the obj when viewed looks like this: (see attachment)...is this correct? 

![output0001](https://user-images.githubusercontent.com/55971786/65870905-e5b7af80-e39a-11e9-9bc6-4478bf1bd27d.jpg)

_Originally posted by @alakhag in https://github.com/thmoa/semantic_human_texture_stitching/issues/2#issuecomment-536052365_

**Comment by thmoa** [comment]
please do not open issues not related to the code. thank you.
