### ISSUE TITLE
 how to set camera_f while generating frame_data.pkl?

### ISSUE THREAD

**Issue by ZhiRuoo** [thmoa/semantic_human_texture_stitching#15]
Hi @thmoa , many thanks for the code. 

I am successfully able use octopus to generate obj and apply texture on it. But the output looks larger than actual. Is it due to wrong focal length value?

I used a OnePlus 5 mobile camera with rear **focal length of 24mm** for frames generation. Could you please tell me how to use this 24mm to set camera_f while generating frame_data.pkl?

Thanks in advance...

**Comment by thmoa** [comment]
Again this question is unrelated to the project! **ONLY** open issues when there is a bug in the code or something is absolutely unclear.

If you use Octopus, use the same focal-length as assumed by Octopus. To learn about camera calibration and focal length, please consult Google.
