### ISSUE TITLE
AttributeError: 'GaussianMixture' object has no attribute 'means_'

### ISSUE THREAD

**Issue by Eby-123** [thmoa/semantic_human_texture_stitching#17]
@thmoa 
Hi，when I run the code "bash run_sample.sh",sometimes it run to the end without any error,but sometimes it returns errors as follows:

```
Traceback (most recent call last):
  File "step3_stitch_texture.py", line 83, in <module>
    main(args.unwrap_dir, args.segm_template, args.gmm, args.out_file, args.iter)
  File "step3_stitch_texture.py", line 48, in main
    texture_agg, labels = texture.add_iso(isos[rl], visibilities[rl], rl, inpaint=i == (num_iter-1))
  File "/home/wuyibin/MultiGarmentNetwork-master_python3/semantic_human_texture_stitching-master/tex/texture.py", line 112, in add_iso
    diff = data.reshape(-1, 1, 3) - self.gmms[color_id].means_
AttributeError: 'GaussianMixture' object has no attribute 'means_'
```

Any advice about resolving this error will be appreciated.

**Comment by thmoa** [comment]
This means you are trying to read a GaussianMixture for a segment that has not been computed in the step before.

Sorry, you would need to debug for yourself. If you find a bug, feel free to submit a PR.

**Comment by Qingcsai** [comment]
@Eby-123 Hi, I met the same question as yours, did u solve it ? I still can't debug myself successfully.
