### ISSUE TITLE
edge seams artificats in textured models

### ISSUE THREAD

**Issue by sawar7577** [thmoa/semantic_human_texture_stitching#18]
I ran the octopus pipeline which uses this repo for generating texture. The textured models have artificats at edge seams, was this done deliberately to separate out different parts?

**Comment by thmoa** [comment]
Make sure inpaint after stitching.

https://github.com/thmoa/semantic_human_texture_stitching/blob/7beaa44ba4a96ecc6397766f1871940ceba834f5/tex/texture.py#L130
