### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by ujjawalcse** [thmoa/semantic_human_texture_stitching#19]
Hi @thmoa ,
I could successfully created the **frames data** and their corresponding **segmentations data** using **PGN** segmentation. For the second step, I executed the **octopus(run_demo.sh)**. But it's generating only 3D model 

> sample.obj

. Then I figured out to save vertices i.e 

> pred['vertices'][0]

 in infer_single.py, But again it is producing a single vertices.pkl file for overall frames.
How can i save vertices for every frames?
Please help as it will be helpful to create frame_data.py
Thanks.

**Comment by thmoa** [comment]
https://github.com/thmoa/semantic_human_texture_stitching/issues/12#issuecomment-541016996

**Comment by ujjawalcse** [comment]
Thanks for helping @thmoa.
I was doing the same thing. But i got misguided by observing your
frame_data.pkl. I printed the value of len(pkl_data['vertices']) and it's 8.
Then,i thought vertices are taken for every frames.
Sorry for inconvenience.
