### ISSUE TITLE
How do I texture an image into obj.file?

### ISSUE THREAD

**Issue by gucasbrg** [thmoa/semantic_human_texture_stitching#2]
I use octopus  in order to generate sample.obj , and use this project to generate  sample_texture.jpg, 
but obj file warning "This mesh does not have any texture coordinates." ,what solution can I get ?  tks

**Comment by luovang** [comment]
It confused me too. help, please.

**Comment by vangogh0318** [comment]
I met the same problem. anyone solved it ?

**Comment by thmoa** [comment]
Include texture coordinates (vt, ft), when writing the obj file. They are provided in this repository.

**Comment by fasogbon** [comment]
@thmoa Please can you show an example or output .obj where the vertices, faces and texture coordinates is affixed.
I tried to create .obj file with contents v: x y z, f: a b c, vt: u v  
The vt is the textured vertices from the created raster. I am unable to view the textured surface using meshlab (it doesnt provide any possibility to input the textured image).

Do you have a better suggestion on how to go about viewing this textured mesh? Thank you

**Comment by thmoa** [comment]
https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format

**Comment by fasogbon** [comment]
okay thanks! In the meantime, i will go check your other work on videoavatar

**Comment by lyrgwlr** [comment]
@thmoa ,
Hi, I want to put this repository's output(*.jpg file) into octopus's output(*.obj file).
And like you said:
Include texture coordinates (vt, ft), when writing the obj file. They are provided in this repository.

But I can't find the texture coordinates in the code. Do you mean gmm.pkl file in step2 output? Can you tell me how to edit the *.obj file in order to include the human texture information provided by this repository? Thanks a lot!

**Comment by lyrgwlr** [comment]
@fasogbon 
Hi, have you solved this? Please can you give me some specific hints? Thanks

**Comment by QHan1st** [comment]
> Include texture coordinates (vt, ft), when writing the obj file. They are provided in this repository.

I followed your advice,included texture coordinates (vt,ft) into the .obj file,but it still show the orignal naked mesh model.Could you tell me how should i do?Thanks.
@thmoa

**Comment by lyrgwlr** [comment]
@hanqing1 
Hi, can you please tell me where the texture coodinates (vt, ft) are in the codes?
Thanks a lot.

**Comment by fasogbon** [comment]
I have been very busy and can't still reply properly. 
Go online and download a .obj format file. There you will see how vertex v, vertex texture vt, face f are arranged. There are MATLAB files online to read .obj file and specifying the texture image. That should help you on how to create your .obj from octopus output

**Comment by lyrgwlr** [comment]
@fasogbon 
I think the pipeline is:
1. Add vt and f in .obj file.
2. Use some software like 3dMax to put the texture image on the model
Is that right?

**Comment by QHan1st** [comment]
> @fasogbon
> I think the pipeline is:
> 
>     1. Add vt and f in .obj file.
> 
>     2. Use some software like 3dMax to put the texture image on the model
>        Is that right?
>        And where are the texture coordinates? Are they in this repository or in the Octopus repository?

I regarded the output of both file basicModel_vt.npy and basicModel_ft.npy as (vt,ft),and inputed them into .obj file.but there is no expected results.I guess that the label f in the .obj file is related to the texture.but I dont know how to add the vt index into the label f. Do you have any idea?

**Comment by lyrgwlr** [comment]
@hanqing1 
as you said, basicModel_ft.npy shape=(13776, 3). And the .obj file from octopus's output includes 13776 lines label f. 
I think you should edit like this:
original:    f    xx xx xx
changed:  f    xx/vt[0][0]+1  xx/vt[0][1]+1  xx/vt[0][2]+1
                             ...
                 f    xx/vt[13775][0]+1  xx/vt[13775][1]+1  xx/vt[13775][2]+1

But changing this isn't mean visualizing the model with texture information. Something need to be done next. Can you keep contacting with me? Thanks

**Comment by QHan1st** [comment]
@thmoa @lyrgwlr
I will try your suggestions.Keep contact.Thank you!

**Comment by lyrgwlr** [comment]
@fasogbon , @thmoa , @hanqing1 
Now I have the .obj file with texture coordinates and the texture image.
I search some methods online to get a textured mesh. But it seems only some software can solve it like Unity, 3dMax or something else. I am a totally new in 3D stuff. 
If there are any codes to put the texture image to the 3d mesh?

**Comment by fasogbon** [comment]
https://www.mathworks.com/matlabcentral/fileexchange/20307-display_obj

This MATLAB script will read your .obj file and display it when you provide the associated textured (find an example .obj online, the folder should contain .obj and associated .PNG or .jpg unwrap texture). Goodluck. Please read how .obj file works

**Comment by lyrgwlr** [comment]
@fasogbon 
Thanks! I will try that later.
And I have a little question after I read the .obj file structure.
I just add the vt label into the .obj file from Octopus. 
So the f label is like f v_index/vt_index v_index/vt_index v_index/vt_index
I didn't add the vn label, is that necessary?

**Comment by fasogbon** [comment]
You don't need vn. If you use vn then your face will be f v_index/vt_index/vn_index

Goodluck

**Comment by lyrgwlr** [comment]
@fasogbon 
Thanks, I solved it using the matlab code provided by you.

**Comment by QHan1st** [comment]
@lyrgwlr I want to know what your results of textured human looks like?And my results doesnt look good.

**Comment by lyrgwlr** [comment]
![out](https://user-images.githubusercontent.com/25834598/63830451-bfb77d80-c99e-11e9-9b9c-6fa39e2917db.png)
I used the Octopus's provided data. The output of the display_out.m file is like this:

It's a 3d model that can be drugged. But it's a .fig file. If there is any format that can show this textured human without Matlab? @fasogbon

**Comment by QHan1st** [comment]
@lyrgwlr where is the display_out.m file ? I cant fint it in the Octopus project.

**Comment by lyrgwlr** [comment]
@hanqing1 
https://www.mathworks.com/matlabcentral/fileexchange/20307-display_obj

**Comment by alakhag** [comment]
A simple solution works for me

1. Download the SMPL model for Unity.
2. Convert the .fbx file to .obj file
3. Copy the vt and f coordinates provided in that file
4. Create my own material as follows:
i. mymtl.mtl
newmtl MyMaterial
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
Ke 0.0 0.0 0.0
Ni 1.450000
d 1.000000
illum 2
map_Ka tex1.jpg

Where tex1.jpg is generated texture's UV map


ii. Change the .obj file generated by Octopus as follows.
Remove the f coordinates and copy the vt and f coordinated described above
Add "mtllib mymtl.mtl" in the start of the file, and "usemtl MyMaterial" at the end.
Now the .obj file contains the texture.

**Comment by thmoa** [comment]
There is no need to copy the quad faces from SMPL fbx. Simply use the texture coords provided in `assets`.

**Comment by alakhag** [comment]
Yes. I changed the pipeline and doing that now. It works the same, I believe, because vt and f define UV map, and the mapping is same.

Note: I had to add 1 for every f and ft values because the indexing starts from 0, when it should actually start from 1.

**Comment by thmoa** [comment]
This is correct.

Once again please see: https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format

**Comment by FighterFong** [comment]
> 2\. .fbx

what and where is the .fbx file?

**Comment by FighterFong** [comment]
> A simple solution works for me
> 
> 1. Download the SMPL model for Unity.
> 2. Convert the .fbx file to .obj file
> 3. Copy the vt and f coordinates provided in that file
> 4. Create my own material as follows:
>    i. mymtl.mtl
>    newmtl MyMaterial
>    Ka 1.000 1.000 1.000
>    Kd 1.000 1.000 1.000
>    Ks 0.000 0.000 0.000
>    Ke 0.0 0.0 0.0
>    Ni 1.450000
>    d 1.000000
>    illum 2
>    map_Ka tex1.jpg
> 
> Where tex1.jpg is generated texture's UV map
> 
> ii. Change the .obj file generated by Octopus as follows.
> Remove the f coordinates and copy the vt and f coordinated described above
> Add "mtllib mymtl.mtl" in the start of the file, and "usemtl MyMaterial" at the end.
> Now the .obj file contains the texture.

![Screenshot 2019-12-05 at 7 28 40 PM](https://user-images.githubusercontent.com/20882610/70231596-98d6c780-1795-11ea-9ab8-7c8020dc6a64.png)
![image](https://user-images.githubusercontent.com/20882610/70231759-e81cf800-1795-11ea-8644-fef4089732cd.png)
![Uploading Screenshot 2019-12-05 a

mtl file:
newmtl MyMaterial
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.000 0.000 0.000
Ke 0.0 0.0 0.0
Ni 1.450000
d 1.000000
illum 2
map_Ka sample_texture.jpg

sample_texture.jpg
![Screenshot 2019-12-05 at 7 56 38 PM](https://user-images.githubusercontent.com/20882610/70233361-64650a80-1799-11ea-8aec-c54b33b97832.png)



I copy basicModel_vt.npy and basicModel_f.npy to the obj file, also add 1,but why the result is show as  above?Is mtl color setting error?

**Comment by thmoa** [comment]
https://github.com/thmoa/videoavatars/blob/master/step2_consensus.py#L141

**Comment by lemon1220** [comment]
> Yes. I changed the pipeline and doing that now. It works the same, I believe, because vt and f define UV map, and the mapping is same.
> Note: I had to add 1 for every f and ft values because the indexing starts from 0, when it should actually start from 1.

hi friends,
can you tell me how to add ?thanks for your help

**Comment by lemon1220** [comment]
> @fasogbon , @thmoa , @hanqing1
> Now I have the .obj file with texture coordinates and the texture image.
> I search some methods online to get a textured mesh. But it seems only some software can solve it like Unity, 3dMax or something else. I am a totally new in 3D stuff.
> If there are any codes to put the texture image to the 3d mesh?

hi friend:
can you kindly tell me how can i get .obj with texture coordinates ?? thanks for your help

**Comment by lemon1220** [comment]
> @fasogbon , @thmoa , @hanqing1
> Now I have the .obj file with texture coordinates and the texture image.
> I search some methods online to get a textured mesh. But it seems only some software can solve it like Unity, 3dMax or something else. I am a totally new in 3D stuff.
> If there are any codes to put the texture image to the 3d mesh?

hi friend:
can you kindly tell me how can i get .obj with texture coordinates ?? thanks for your help

**Comment by lemon1220** [comment]
I have solved this problem ,just add vt and change f  in .obj

**Comment by lemon1220** [comment]
I have solved this problem ,just add vt and change f  in .obj

**Comment by Frank-Dz** [comment]
> I use octopus in order to generate sample.obj , and use this project to generate sample_texture.jpg,
> but obj file warning "This mesh does not have any texture coordinates." ,what solution can I get ? tks

Hi~ @gucasbrg  May I ask how to use octopus in order to generate sample.obj ?
I searched on google and  did not find the code repo.
Thanks in advance!

Best,
Frank

**Comment by zandls-lovelulu** [comment]
> I have solved this problem ,just add vt and change f in .obj


Can you teach me how to attach. JPG to the. Obj model, please

**Comment by zhanghongyong123456** [comment]
> I have solved this problem ,just add vt and change f in .obj

could you tell me how to change f, i join (vt,ft) in .obj,but no display

**Comment by mwang259** [comment]
> I have solved this problem ,just add vt and change f in .obj

@lemon1220  Could you tell me how to add vt and chang f in sample .obj? Thank you so much!
