### ISSUE TITLE
question about basicModel_seam

### ISSUE THREAD

**Issue by quyanqiu** [thmoa/semantic_human_texture_stitching#20]
Hey,sorry for bothering you,just a little question about the basicModel_seam.npy,because I would like to replace smpl with some other body model.
but I do not know the specific meaning of this npy files,I know that seam is used to split the mesh surface and make uv unwarp ,the shape of your seam is [1360,4],I know 1360 means there are 1360 edges that consist the seams,but why the shape[1] is 4？what is the specific meaning of each dimension ?
Thanks a lot for your response bro : )

**Comment by thmoa** [comment]
Those are two edges represented by 2 vertices each.

**Comment by quyanqiu** [comment]
@thmoa ,Thanks,but I do not know why there are two edges.With my opinion,a seam are consist with several edge,each edge are formed by 2 vertices,so the shape should be [1360,2] instead of [1360,4],
to figure out that , I visualize your [1360,4] array,for first 2 dimension [1360,:2],the seam island is liked below:
![152277af155abbd932e3c856c9a539e](https://user-images.githubusercontent.com/11349003/81143717-143ae000-8fa5-11ea-922a-b56c3a3a70de.png)
for last 2 dimension [1360,2:],the seam island is liked below:
![c98993c938bf327031dbffb3c869eb6](https://user-images.githubusercontent.com/11349003/81143762-2fa5eb00-8fa5-11ea-8bec-0ba911cfcaca.png)
It seemes that picture 2 is a part of picture 1 ,and it split each seam seperately
