### ISSUE TITLE
a problem about generating texture 

### ISSUE THREAD

**Issue by hzhao1997** [thmoa/semantic_human_texture_stitching#22]
First of all, Thank for your code. I am trying to run your code on my data and I follow your steps, but why it looks like this?

     I think the input image is not aligned with the vertices produced by Octopus, but how to solve this problem? Thanks again~
![sample_texture](https://user-images.githubusercontent.com/32841739/89144643-df78fd80-d580-11ea-9d29-b67c701b9322.jpg)

**Comment by thmoa** [comment]
https://github.com/thmoa/semantic_human_texture_stitching/issues/12#issuecomment-536658830
