### ISSUE TITLE
Another problem about generating texture map

### ISSUE THREAD

**Issue by hzhao1997** [thmoa/semantic_human_texture_stitching#23]
I have optimized octopus enough times, and get correct mesh to obtain plausible partial texture map. Then I merge all of these texture map and get results as below. How should I fix this problem? Thanks~
![sample_texture](https://user-images.githubusercontent.com/32841739/90308630-865f8100-df13-11ea-8bae-23f1521c2be3.jpg)

**Comment by hzhao1997** [comment]
![00000_unwrap](https://user-images.githubusercontent.com/32841739/90308825-45686c00-df15-11ea-83b2-bb8ebc5334d8.jpg)
![00001_unwrap](https://user-images.githubusercontent.com/32841739/90308827-47322f80-df15-11ea-904b-10c858495b76.jpg)
![00002_unwrap](https://user-images.githubusercontent.com/32841739/90308828-48635c80-df15-11ea-8926-e8af7d355622.jpg)
![00003_unwrap](https://user-images.githubusercontent.com/32841739/90308831-49948980-df15-11ea-9dc8-bac060ff27b0.jpg)
![00004_unwrap](https://user-images.githubusercontent.com/32841739/90308832-4a2d2000-df15-11ea-8ac4-ad86878be60a.jpg)
![00005_unwrap](https://user-images.githubusercontent.com/32841739/90308833-4ac5b680-df15-11ea-884b-f8fc9e94f327.jpg)
![00006_unwrap](https://user-images.githubusercontent.com/32841739/90308834-4b5e4d00-df15-11ea-91b9-ccf3d733b936.jpg)
![00007_unwrap](https://user-images.githubusercontent.com/32841739/90308835-4bf6e380-df15-11ea-8f3e-1137d014093b.jpg)

**Comment by thmoa** [comment]
These are not the merged textured but the partial ones.
