### ISSUE TITLE
iso==0.0.3   cannot import name 'Isomapper' from 'iso'

### ISSUE THREAD

**Issue by yutao007** [thmoa/semantic_human_texture_stitching#24]
Step 1: make unwraps...
Traceback (most recent call last):
  File "step1_make_unwraps.py", line 16, in <module>
    from tex.texture import TextureData
  File "/home/Downloads/semantic_human_texture_stitching/tex/texture.py", line 11, in <module>
    from iso import Isomapper
ImportError: cannot import name 'Isomapper' from 'iso' (/home/anaconda3/envs/vibe-env/lib/python3.7/site-packages/iso/__init__.py)
Step 2: make priors...
step2_segm_vote_gmm.py:82: RuntimeWarning: divide by zero encountered in true_divide
  unaries = np.ascontiguousarray((1 - voting / len(iso_files)) * 10)
step2_segm_vote_gmm.py:82: RuntimeWarning: invalid value encountered in true_divide
  unaries = np.ascontiguousarray((1 - voting / len(iso_files)) * 10)
Traceback (most recent call last):
  File "step2_segm_vote_gmm.py", line 146, in <module>
    main(args.unwrap_dir, args.segm_out_file, args.gmm_out_file)
  File "step2_segm_vote_gmm.py", line 86, in main
    edge_idx = pkl.load(open('assets/basicModel_edge_idx_1000.pkl', 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 80: ordinal not in range(128)
Step 3: stitch texture...
Traceback (most recent call last):
  File "step3_stitch_texture.py", line 14, in <module>
    from tex.texture import Texture
  File "/home/Downloads/semantic_human_texture_stitching/tex/texture.py", line 11, in <module>
    from iso import Isomapper
ImportError: cannot import name 'Isomapper' from 'iso' (/home/anaconda3/envs/vibe-env/lib/python3.7/site-packages/iso/__init__.py)

**Comment by yutao007** [comment]
is this only just to  python3 ?

**Comment by yutao007** [comment]
from .iso import Isomapper      doing  this right  
but    UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 80: ordinal not in range(128)

**Comment by thmoa** [comment]
this is python2 code

**Comment by yutao007** [comment]
ok ok  ok  you are right .but i have done it in python3

**Comment by utc1205** [comment]
how do you resolve this problem ? i also want to use it in python3 @yutao007

**Comment by zandls-lovelulu** [comment]
> ok ok ok you are right .but i have done it in python3

hello，I also encountered this problem, can you give me some advice?
