### ISSUE TITLE
question about basicModel_seams.npy and basicModel_edge_idx_1000.pkl ? 

### ISSUE THREAD

**Issue by utc1205** [thmoa/semantic_human_texture_stitching#25]
Hi @thmoa, sorry for bothering you, I have a little question about the basicModel_seam.npy and basicModel_edge_idx_1000.pkl.  I guessed they were index of vertices of seam in basicModel_seam.npy, but the maximum value is much far beyond the basicmodel vertices' number.  Can you explain what are they in two files?  Thanks.

**Comment by thmoa** [comment]
the code should explain this. please check yourself.

I believe we have texels here and not vertices.
