### ISSUE TITLE
GCO naming

### ISSUE THREAD

**Issue by brejchajan** [thmoa/semantic_human_texture_stitching#27]
Hi, thank you very much for the code!

I am experiencing error in step2_segm_vote_gmm.py:
` File "step2_segm_vote_gmm.py", line 107, in main
    gc = gco.gco()`

The problem is resolved by changing `gco.gco()` to `gco.GCO()`.

Furthermore, on the next line, there is  `gc.createGeneralGraph(1000 ** 2, pairwise.shape[0], True)`, but should be `gc.create_general_graph(1000 ** 2, pairwise.shape[0], True)`. 

There are probably more places with the wrong naming of the GCO library. Shall I create a pull request with a fix?

I am on MacOS 10.15.7, homebrew python2.7, GCO version 3.0.2 (master, commit: `1203f5a7c0e458de7dc7191f7d5f89b9ce985e7a`).

**Comment by thmoa** [comment]
Yes please submit a PR. Looks like gco changed the naming convention in a newer version. Thank you!
