### ISSUE TITLE
Consultation on the effect of generated texture map

### ISSUE THREAD

**Issue by code-conquer** [thmoa/semantic_human_texture_stitching#33]
Hello, I recently tried to use your code to generate UV texture images, but there are problems in the arm area. Do you know what caused this？

![sample_texture](https://user-images.githubusercontent.com/36815230/141764315-b064483c-fab8-4813-a4df-e3cdbe66c62d.jpg)
>

**Comment by thmoa** [comment]
Yes. Not very precise 2D overlap of the estimated pose and the image.
