### ISSUE TITLE
How texture image apply to 3D model

### ISSUE THREAD

**Issue by mwang259** [thmoa/semantic_human_texture_stitching#35]
Hello guys! I got the 3D human model by running the octopus project. Then I run the semantic_human_texture_stitching project, it generated the texture image and segm image by . they are shown in order in the below:

![model](https://user-images.githubusercontent.com/105466900/179850458-c137e2c7-2fd5-4a94-bddc-44e0c3acbd45.jpg)
![texture](https://user-images.githubusercontent.com/105466900/179850475-8f071141-bf80-4c2b-ba94-f542749f73ed.jpg)
![seg](https://user-images.githubusercontent.com/105466900/179850485-fe73448a-3c89-42a9-87a6-71eca801b6b8.jpg)

But when I pasted texture_image(second image) to 3D model(first image) in blender and unity, this model is always black without clothing texture. I hope friends who know what happend could help me, thank you in advance!

![render](https://user-images.githubusercontent.com/105466900/179851774-3ce63f1d-64df-439e-8a22-ae1cd27e28db.jpg)

**Comment by thmoa** [comment]
Please make sure to save the texture coordinates in the obj file.
