### ISSUE TITLE
How to save texture cooradinate

### ISSUE THREAD

**Issue by mwang259** [thmoa/semantic_human_texture_stitching#36]
I have got the sample.obj and sample_texture.jpg. But the project also needs texture coordinates. Is there someone has solved this problem. How to save the texture coordinates in the obj file. This is the last step I need, and I still don't know how to fix it.  Could you guys help me. Thank you so much! 

![render](https://user-images.githubusercontent.com/105466900/186282438-7f202417-04f8-4eb8-a936-bebe8738a270.jpg)

**Comment by thmoa** [comment]
https://github.com/thmoa/semantic_human_texture_stitching/issues/2#issuecomment-562622931
