### ISSUE TITLE
Mismatched Texture coming from the New data 

### ISSUE THREAD

**Issue by vamsi131550** [thmoa/semantic_human_texture_stitching#5]
##Semantic Texture stitching is not giving the correct texure map when run with the new data taken from the camera by us .I have Read the Research paper clearly
The data has been given to the octopus and predicted the frame data.pkl  
I have given this framedata.pkl , color images , semantic segmentations of new data to the texture stitching method 

But getting the wrong results . Mismatching has been occuring at the faces badly and at the belly side of the body.at some parts the texture has been tilted and rotated.

**Comment by thmoa** [comment]
Please: If you open an issue, describe what the issue is and how the code is affected. If possible fix the bug yourself and open a PR.

From your description, I cannot tell if there is an issue with our code or your way of using it.
