### ISSUE TITLE
frame_data.pkl

### ISSUE THREAD

**Issue by DomhnallBoyle** [thmoa/semantic_human_texture_stitching#6]
Hi @thmoa, 

I was wondering how to generate the frame_data.pkl specifically this part: 

"vertices": [list of per frame SMPL vertices in camera coordinates]

Are these the vertices from the .obj file? Also, is this dictionary entry a list within a list so each frame is basically an inner list of these .obj vertices?

Thanks

**Comment by thmoa** [comment]
yes list of list of vertices

**Comment by DomhnallBoyle** [comment]
Is there a way to generate the per-frame vertices using octopus? This is probably wrong but doesn't octopus generate vertices for the combined frames?

**Comment by thmoa** [comment]
yes there is. please check the demo.

**Comment by takumi-R** [comment]
Sorry about my bad English.
I know that this was asked multiple times but I still have a hard time generating [list of per frame SMPL vertices in camera coordinates].
Can you please give us more detailed information about it?
Using frame_data.pkl in demo generates same texture as shown in example but when I generate it by octopus I could not regenerate the same result as yours.
I tried generating models per-frame and rotating order of input images but it did not work.
Even a small amount of information is greatly appreciated.

Thank you

**Comment by WangChunxuCPP** [comment]
Could you tell me how to get the "vertices"? Thank you!  @DomhnallBoyle
