### ISSUE TITLE
A implement question in your paper

### ISSUE THREAD

**Issue by quyanqiu** [thmoa/semantic_human_texture_stitching#9]
Hi
   when I try to implement your paper"detail video avatar",a liittle question confuse me. In the subdivided smpl body model,you constrcut a finer model Mf(β; θ; D; s) consist of 110210 vertics and 220416 faces. I noticed that shape blend shape β,pose blend shape θ,blend skinning function W seems to be out of dated,even the joint regressor J.I wonder that how you guys update the original smpl parameter β; θ; W;J.Looking forward to your responding.

**Comment by thmoa** [comment]
Simply interpolate it too.

**Comment by zhanghongyong123456** [comment]
> Hi
> when I try to implement your paper"detail video avatar",a liittle question confuse me. In the subdivided smpl body model,you constrcut a finer model Mf(β; θ; D; s) consist of 110210 vertics and 220416 faces. I noticed that shape blend shape β,pose blend shape θ,blend skinning function W seems to be out of dated,even the joint regressor J.I wonder that how you guys update the original smpl parameter β; θ; W;J.Looking forward to your responding.

hi，how  to do this，for add f
